---
name: build

on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: List files
        run: ls -latr
      - name: Checkout - fork
        uses: actions/checkout@v4
        continue-on-error: true
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          path: fork
      - name: List files - fork
        run: ls -latr fork
        continue-on-error: true
      - name: Print test secret sha256
        run: echo ${{ secrets.TEST_SECRET }} | sha256sum
